[package]
name = "chemrust-nasl-app"
version = "0.1.0"
edition = "2021"
authors = ["TonyWu20"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
castep-cell-io = "0.1.2"
castep-periodic-table = "0.4"
chemrust-nasl = {path = "../chemrust-nasl"}
